config/routes.rb
Rails.application.routes.draw do
  resources :alquilers
  resources :repartos
  resources :casetes
  resources :actors
  resources :peliculas
  resources :miembros
  root 'peliculas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/miembro.rb
class Miembro < ApplicationRecord
end

app/controllers/miembros_controller.rb
class MiembrosController < ApplicationController
  before_action :set_miembro, only: [:show, :edit, :update, :destroy]

  # GET /miembros
  # GET /miembros.json
  def index
    @miembros = Miembro.all
  end

  # GET /miembros/1
  # GET /miembros/1.json
  def show
  end

  # GET /miembros/new
  def new
    @miembro = Miembro.new
  end

  # GET /miembros/1/edit
  def edit
  end

  # POST /miembros
  # POST /miembros.json
  def create
    @miembro = Miembro.new(miembro_params)

    respond_to do |format|
      if @miembro.save
        format.html { redirect_to @miembro, notice: 'Miembro was successfully created.' }
        format.json { render :show, status: :created, location: @miembro }
      else
        format.html { render :new }
        format.json { render json: @miembro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /miembros/1
  # PATCH/PUT /miembros/1.json
  def update
    respond_to do |format|
      if @miembro.update(miembro_params)
        format.html { redirect_to @miembro, notice: 'Miembro was successfully updated.' }
        format.json { render :show, status: :ok, location: @miembro }
      else
        format.html { render :edit }
        format.json { render json: @miembro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miembros/1
  # DELETE /miembros/1.json
  def destroy
    @miembro.destroy
    respond_to do |format|
      format.html { redirect_to miembros_url, notice: 'Miembro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_miembro
      @miembro = Miembro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def miembro_params
      params.require(:miembro).permit(:nombre, :telefono, :direccion)
    end
end

app/helpers/miembros_helper.rb
module MiembrosHelper
end

app/views/miembros/_form.html.erb
<%= form_with(model: miembro, local: true) do |form| %>
  <% if miembro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(miembro.errors.count, "error") %> prohibited this miembro from being saved:</h2>

      <ul>
      <% miembro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/miembros/edit.html.erb
<h1>Editing Miembro</h1>

<%= render 'form', miembro: @miembro %>

<%= link_to 'Show', @miembro %> |
<%= link_to 'Back', miembros_path %>

app/views/miembros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Miembros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @miembros.each do |miembro| %>
      <tr>
        <td><%= miembro.nombre %></td>
        <td><%= miembro.telefono %></td>
        <td><%= miembro.direccion %></td>
        <td><%= link_to 'Show', miembro %></td>
        <td><%= link_to 'Edit', edit_miembro_path(miembro) %></td>
        <td><%= link_to 'Destroy', miembro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Miembro', new_miembro_path %>

app/views/miembros/new.html.erb
<h1>New Miembro</h1>

<%= render 'form', miembro: @miembro %>

<%= link_to 'Back', miembros_path %>

app/views/miembros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @miembro.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @miembro.telefono %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @miembro.direccion %>
</p>

<%= link_to 'Edit', edit_miembro_path(@miembro) %> |
<%= link_to 'Back', miembros_path %>