config/routes.rb
Rails.application.routes.draw do
  resources :alquilers
  resources :repartos
  resources :casetes
  resources :actors
  resources :peliculas
  resources :miembros
  root 'peliculas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/casete.rb
class Casete < ApplicationRecord
  belongs_to :pelicula
end

app/controllers/casetes_controller.rb
class CasetesController < ApplicationController
  before_action :set_casete, only: [:show, :edit, :update, :destroy]

  # GET /casetes
  # GET /casetes.json
  def index
    @casetes = Casete.all
  end

  # GET /casetes/1
  # GET /casetes/1.json
  def show
  end

  # GET /casetes/new
  def new
    @casete = Casete.new
  end

  # GET /casetes/1/edit
  def edit
  end

  # POST /casetes
  # POST /casetes.json
  def create
    @casete = Casete.new(casete_params)

    respond_to do |format|
      if @casete.save
        format.html { redirect_to @casete, notice: 'Casete was successfully created.' }
        format.json { render :show, status: :created, location: @casete }
      else
        format.html { render :new }
        format.json { render json: @casete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casetes/1
  # PATCH/PUT /casetes/1.json
  def update
    respond_to do |format|
      if @casete.update(casete_params)
        format.html { redirect_to @casete, notice: 'Casete was successfully updated.' }
        format.json { render :show, status: :ok, location: @casete }
      else
        format.html { render :edit }
        format.json { render json: @casete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casetes/1
  # DELETE /casetes/1.json
  def destroy
    @casete.destroy
    respond_to do |format|
      format.html { redirect_to casetes_url, notice: 'Casete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casete
      @casete = Casete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def casete_params
      params.require(:casete).permit(:pelicula_id, :formato)
    end
end

app/helpers/casetes_helper.rb
module CasetesHelper
end

app/views/casetes/_form.html.erb
<%= form_with(model: casete, local: true) do |form| %>
  <% if casete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(casete.errors.count, "error") %> prohibited this casete from being saved:</h2>

      <ul>
      <% casete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pelicula_id %>
    <%= form.text_field :pelicula_id %>
  </div>

  <div class="field">
    <%= form.label :formato %>
    <%= form.text_field :formato %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/casetes/edit.html.erb
<h1>Editing Casete</h1>

<%= render 'form', casete: @casete %>

<%= link_to 'Show', @casete %> |
<%= link_to 'Back', casetes_path %>

app/views/casetes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Casetes</h1>

<table>
  <thead>
    <tr>
      <th>Pelicula</th>
      <th>Formato</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @casetes.each do |casete| %>
      <tr>
        <td><%= casete.pelicula %></td>
        <td><%= casete.formato %></td>
        <td><%= link_to 'Show', casete %></td>
        <td><%= link_to 'Edit', edit_casete_path(casete) %></td>
        <td><%= link_to 'Destroy', casete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Casete', new_casete_path %>

app/views/casetes/new.html.erb
<h1>New Casete</h1>

<%= render 'form', casete: @casete %>

<%= link_to 'Back', casetes_path %>

app/views/casetes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pelicula:</strong>
  <%= @casete.pelicula %>
</p>

<p>
  <strong>Formato:</strong>
  <%= @casete.formato %>
</p>

<%= link_to 'Edit', edit_casete_path(@casete) %> |
<%= link_to 'Back', casetes_path %>