config/routes.rb
Rails.application.routes.draw do
  resources :alquilers
  resources :repartos
  resources :casetes
  resources :actors
  resources :peliculas
  resources :miembros
  root 'peliculas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alquiler.rb
class Alquiler < ApplicationRecord
  belongs_to :casete
  belongs_to :miembro
end

app/controllers/alquilers_controller.rb
class AlquilersController < ApplicationController
  before_action :set_alquiler, only: [:show, :edit, :update, :destroy]

  # GET /alquilers
  # GET /alquilers.json
  def index
    @alquilers = Alquiler.all
  end

  # GET /alquilers/1
  # GET /alquilers/1.json
  def show
  end

  # GET /alquilers/new
  def new
    @alquiler = Alquiler.new
  end

  # GET /alquilers/1/edit
  def edit
  end

  # POST /alquilers
  # POST /alquilers.json
  def create
    @alquiler = Alquiler.new(alquiler_params)

    respond_to do |format|
      if @alquiler.save
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully created.' }
        format.json { render :show, status: :created, location: @alquiler }
      else
        format.html { render :new }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alquilers/1
  # PATCH/PUT /alquilers/1.json
  def update
    respond_to do |format|
      if @alquiler.update(alquiler_params)
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully updated.' }
        format.json { render :show, status: :ok, location: @alquiler }
      else
        format.html { render :edit }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alquilers/1
  # DELETE /alquilers/1.json
  def destroy
    @alquiler.destroy
    respond_to do |format|
      format.html { redirect_to alquilers_url, notice: 'Alquiler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alquiler
      @alquiler = Alquiler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alquiler_params
      params.require(:alquiler).permit(:casete_id, :miembro_id, :fecha_alquiler, :fecha_devolucion)
    end
end

app/helpers/alquilers_helper.rb
module AlquilersHelper
end

app/views/alquilers/_form.html.erb
<%= form_with(model: alquiler, local: true) do |form| %>
  <% if alquiler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alquiler.errors.count, "error") %> prohibited this alquiler from being saved:</h2>

      <ul>
      <% alquiler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :casete_id %>
    <%= form.text_field :casete_id %>
  </div>

  <div class="field">
    <%= form.label :miembro_id %>
    <%= form.text_field :miembro_id %>
  </div>

  <div class="field">
    <%= form.label :fecha_alquiler %>
    <%= form.date_select :fecha_alquiler %>
  </div>

  <div class="field">
    <%= form.label :fecha_devolucion %>
    <%= form.date_select :fecha_devolucion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alquilers/edit.html.erb
<h1>Editing Alquiler</h1>

<%= render 'form', alquiler: @alquiler %>

<%= link_to 'Show', @alquiler %> |
<%= link_to 'Back', alquilers_path %>

app/views/alquilers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alquilers</h1>

<table>
  <thead>
    <tr>
      <th>Casete</th>
      <th>Miembro</th>
      <th>Fecha alquiler</th>
      <th>Fecha devolucion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alquilers.each do |alquiler| %>
      <tr>
        <td><%= alquiler.casete %></td>
        <td><%= alquiler.miembro %></td>
        <td><%= alquiler.fecha_alquiler %></td>
        <td><%= alquiler.fecha_devolucion %></td>
        <td><%= link_to 'Show', alquiler %></td>
        <td><%= link_to 'Edit', edit_alquiler_path(alquiler) %></td>
        <td><%= link_to 'Destroy', alquiler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alquiler', new_alquiler_path %>

app/views/alquilers/new.html.erb
<h1>New Alquiler</h1>

<%= render 'form', alquiler: @alquiler %>

<%= link_to 'Back', alquilers_path %>

app/views/alquilers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Casete:</strong>
  <%= @alquiler.casete %>
</p>

<p>
  <strong>Miembro:</strong>
  <%= @alquiler.miembro %>
</p>

<p>
  <strong>Fecha alquiler:</strong>
  <%= @alquiler.fecha_alquiler %>
</p>

<p>
  <strong>Fecha devolucion:</strong>
  <%= @alquiler.fecha_devolucion %>
</p>

<%= link_to 'Edit', edit_alquiler_path(@alquiler) %> |
<%= link_to 'Back', alquilers_path %>